name: firebasecrud
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.7
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  get: 4.6.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
